Proagenda2030/upgrade 2.021.12b (#3)
* Store ConfigurationFile content in a public place

…so that installations using local storage can customize logos and the
login page background

* Clean up unused constants and imports

* Clean up more trash

* export creator styles done

* split out main parts

* start building exports list

* move bulk edit specific styles for simple-table to separate file

* exports list looks done

* version count

* Cleaned up tests and updated the API Docs

* Fix tests broken by formpack export changes

* define exports settings data interface and reflux actions

* Remove incorrect export constants

* hooking up in progress, geojson checkbox

* add disable property option for TextBox component

* Add tests for filtering csv and xls exports

* Allow for `flatten` property to be included in export settings

* creating and updating hooked up

* fighting with payload errors

* Add `unique_together` constraint for export settings model

* Do some housekeeping

* cleanup payload properly and allow deleting settings

* Allow blank name fields in export settings

* todo notes

* done except two improvements

* preselect export setting

* Move export task queryset filters to filters.py, add ordering filter

* Migrate `/exports` to `/api/v2/exports`

* put nameless export name in const

* fix fuzzy search wrong results caused by location parameter

* Revert v1 export task changes

* Refactor shared functionality between v1 and v2 into utils

* Clean up exception formatting

* Remove duplicated import

* introduce exportsStore and legacy iframe

* Include documentation for v1 exports endpoint

* Revert dataInterface to old v1 syntax

* Add tests for `/api/v2/exports`

* use new v2 exports enpoint

* fix flatten err

* remove unneeded import

* update paths to common components

* cleanup common components comments

* handle multi language forms

* Update requirements.in with formpack changes for geojson export

* language rendering and confirmation dialogs

* remove old file

* Fixed: Reports view returns a 500 (old relationship to collections still in use, cache for codename does not handle tuples or sets)

* apply permissions to exports components

* WIP changes to export_task view and serializer

* created v2 Imports Endpoint and fixed file name returning `Untitled`

* better searchbox label

* self owned assets in library always display My Library as root breadcrumb

* fix last few bugs found

* added multicheckbox component

* WIP moving css, improved checkbox logic, cleanup

* moved css to seprate file

* add root to checkbox css

* PR css requests

* introduce KoboTagsInput that improves on and fixes few UX issues with current tags inputs

* improve the legacy component too

* allow paste on legacy tags input

* missing commas

* fix small 500 bug (that was not causing any harm to users)

* PR change requests

* use multi checkbox component

* move multiCheckbox to common components

* fix data being mangled too soon and causing filter unselecting issue

* enable easier clearing of assetsTable columns

* Force create asset version on cloning

* Add a unit test to clone asset without version

* fix asset loading hack (param name changed and wasn't updated)

* make kobotagsinput produce unique values only

* Avoid resetting dates when migrating collections…

to assets. Fixes #3033

* return warning if missing attachment

* Migrate v2 export endpoint to nested assets endpoint

* Add missing fields validation in serializer

* Add permissions class and object filtering

* Update export api docs, add filter_backends and permission class

* Clean up filters imports

* Fix broken tests and add some more

* Add type annotations and fix api doc

* changed the `version` field to return the version number and date

* Fix comment typo

* Revert change to API geojson query param

* Update formpack commit hash to latest changes

* Adjusted super user permissions and updated tests

* Update requirements to use formpack changes

* Move export constants to formpack import

* allow `change_submissions` permission to bulk select

* Update formpack requiremt

* Change import from kpi.constants to formpack.constants

* Addressing requested changes

* Updated tests and added a warning for V1 depreciation

* Fixed a typo

* Make requested changes

* adapt to new backend endpoint

* Fix missing directory error when npm building

The full error was:
    Error: ENOENT: no such file or directory, open
    '/srv/src/kpi/jsapp/compiled/extracted-strings.json'

* Fix merge mistake

* Move "migrate()" under "/api/v2/users/<username>/"

* Filter export objects by requesting user for consistency with v1

* Update formpack pip requirement hash

* Fix bug with accessing fields from post data

* Restore test of `geo_question_name`

* Use pytest assert

* Make requested changes

* updated the SSRF split to include `\r`

* Code reformat

* updated the front end to use /api/v2/imports/

* Added permissions to ASSET_TYPE_EMPTY

* Remove unused import

* Add export url to asset detail and fix typo in migrations filename

* add filename to error message

* Fix for submission duplication error

* Inline new method; fail if UUID missing; add TODOs

* moved function and cleaned up code

* Expect bools over stringified bools

* hide hidden, notes and calculate(version) from bulk edit form

* PR changes on translated string format

* hide all calculate rows, not only version one

* dont hide calculate questions in single submission modal

as per chat and standup discussion

* remove analyser

* use established time formatting

* add helpful comments to time formatting functions we use

* Revert COPY_FIELDS order and fix broken tests

* Update formpack requirement and fix tests

* backend no longer uses boolean strings :)

* add comment

* make custom exports columns operate on paths rather than names

* remove console log

* ui tweaks as per #3062

* define a default export settings constant

* better comment text

* rename exports actions filename

* rename exports actions filename

* remove obsolete cleanup function

* select export settings after creating

* rename isVirgin to neutral isInitialised in all files

* make delete export settings button less prominent

* Use year-month-day format for version string and…

add a unit test. Part of #3006

* Add support for `multiple_select`

* Expect an empty string when _submitted_by is None

Tests previously expected _submitted_by to export as None when the source
value was None. Change this to an empty string to match the table view,
single-submission view modal, and a forthcoming update to formpack

* Update requirements to latest formpack hash

* Add tests for multiple_select options

* Include _notes, _tags, _validation_status in list…

of selectable fields when exporting

* make project-downloads a bem element, add (de)select all rows buttons, add more column types to be selected

* better export format default option

* use correct constant access for QUESTION_TYPES

* don't select custom fields toggle when zero fields are selected

* disable (un)select all rows buttons when toggle switch is not enabled

* fix label text

* disable export button when zero rows selected

* rewrite format options list to work with single named language and unnamed language aside named ones

* clear selected defined export on any form changes (include few missing inputs)

* Fix inherited permission class

* user proper permission for deleting export

* add useful note about permissions

* Add test for partial permission in export

* fix headder

Co-authored-by: John N. Milner <john@tmoj.net>
Co-authored-by: joshuaberetta <joshuaberetta@gmail.com>
Co-authored-by: Leszek Pietrzak <leszek@magicznyleszek.xyz>
Co-authored-by: jacquelinemorrissette <jacquelinemariemorrissette@gmail.com>
Co-authored-by: Olivier Leger <olivierleger@gmail.com>
Co-authored-by: Anji Tong <ollejna@gmail.com>